### PR TITLE
Swift 4.2 support

### PR DESCRIPTION
**Pull request by dinsen**

### CODE REVIEW

**Review by freak4pc — CHANGES_REQUESTED** [review]
Hey @Dinsen ! Thanks for your contribution. 

Could you please adjust the CI to build against Swift 4 and Swift 4.2 so we can constantly make sure there's no regression? I'd love to merge it if so. 

Here's an example of how you could do that: 
https://github.com/RxSwiftCommunity/RxStarscream/blob/master/.circleci/config.yml#L27-L38

Thanks!

**Comment by dinsen** [comment]
Hey @freak4pc 
I've committed the changes for CI.

I have not worked with Circle CI before, so please check all made correct.

**Comment by freak4pc** [comment]
@Dinsen Seems like CI is failing - could you confirm the commands build locally on your Mac?

**Comment by dinsen** [comment]
@freak4pc they also failed locally.

I have changed the config back to run build instead of test and rebased. 
There is currently no tests so is it enough just to run build?

**Review by freak4pc — APPROVED** [review]

**Comment by freak4pc** [comment]
Looks good, thanks!

**Pull request merged**
